---

- name: Deploy discord-bot
  hosts: all

  vars_files:
    - vars.yml

  vars:
    image: sergeimaykin/discord-bot:latest
    web_port: 8010
    hostname: botbt.xbbtx.be
    nginx_log_dir: /var/log/nginx/botbt

  roles:
    - geerlingguy.docker

  tasks:

    # Docker

    - name: Ensure docker package is available
      pip:
        name: docker
        state: present

    - name: Ensure a separate network exists
      docker_network:
        name: botbt

    - name: Ensure a database volume exists
      docker_volume:
        name: botbt-db

    - name: Ensure PostgreSQL container runs
      docker_container:
        name: botbt-db
        image: postgres:11-alpine
        hostname: botbt-db
        state: started
        restart: no
        restart_policy: always
        networks:
          - name: botbt
        volumes:
          - botbt-db:/var/lib/postgresql/data
        env:
          POSTGRES_PASSWORD: "{{ db.password }}"

    - name: Ensure main container runs
      docker_container:
        name: botbt-main
        image: "{{ image }}"
        pull: yes
        hostname: botbt
        state: started
        restart: no
        restart_policy: always
        networks:
          - name: botbt
        env:
          TOKEN: "{{ token }}"
          OWNER_ID: "{{ owner_id }}"
          SECRET_KEY: "{{ secret_key }}"
          DB_HOST: "botbt-db"
          DB_NAME: "postgres"
          DB_USER: "postgres"
          DB_PASSWORD: "{{ db.password }}"

    - name: Ensure web container runs
      docker_container:
        name: botbt-web
        image: "{{ image }}"
        pull: yes
        hostname: botbt
        state: started
        restart: no
        restart_policy: always
        networks:
          - name: botbt
        env:
          TOKEN: "{{ token }}"
          OWNER_ID: "{{ owner_id }}"
          SECRET_KEY: "{{ secret_key }}"
          DB_HOST: "botbt-db"
          DB_NAME: "postgres"
          DB_USER: "postgres"
          DB_PASSWORD: "{{ db.password }}"
        published_ports:
          - "127.0.0.1:{{ web_port }}:8000"
        command: /uwsgi.sh

    # Nginx

    - name: Ensure nginx is installed
      package:
        name: nginx
        state: present

    - name: Ensure log dir exists
      file:
        path: "{{ nginx_log_dir }}"
        state: directory

    - name: Install nginx config
      template:
        src: botbt.conf
        dest: /etc/nginx/sites-available/botbt.conf
      notify:
        - reload nginx

    - name: Enable vhost
      file:
        src: /etc/nginx/sites-available/botbt.conf
        dest: /etc/nginx/sites-enabled/botbt.conf
        state: link
      notify:
        - reload nginx

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
